### ISSUE TITLE
Add hdx-python-country to conda-forge

### ISSUE THREAD

**Issue by turnerm** [OCHA-DAP/hdx-python-country#14]

**Comment by kynan** [comment]
This will of course turn into a bit of a rabbit hole: This package depends on [pyphonetics](https://github.com/Lilykos/pyphonetics), which itself is not (yet) packaged for conda. So I've started with [packaging pyphonetics](https://github.com/conda-forge/staged-recipes/pull/21083).

**Comment by kynan** [comment]
That's of course only the start: Next dependency is [libhxl](https://github.com/HXLStandard/libhxl-python), which is also not conda packaged. That again depends on [python-io-wrapper](https://github.com/davidmegginson/python-io-wrapper), also not conda packaged. Next step is [packaging python-io-wrapper](https://github.com/conda-forge/staged-recipes/pull/21084)

**Comment by kynan** [comment]
And, already stuck: python-io-wrapper does not include the license in its source distribution, which blocks conda packaging. Have filed davidmegginson/python-io-wrapper#1.

**Comment by kynan** [comment]
The rabbit hole goes *much much* deeper: next dependency is [hdx-python-utilities](https://github.com/OCHA-DAP/hdx-python-utilities). Filed OCHA-DAP/hdx-python-utilities#10 for packaging that.

**Comment by davidmegginson** [comment]
> And, already stuck: python-io-wrapper does not include the license in its source distribution, which blocks conda packaging. Have filed [davidmegginson/python-io-wrapper#1](https://github.com/davidmegginson/python-io-wrapper/issues/1).
UNLICENSE.md has been in the GitHub repo for 5 years -- I'll have to figure out why it didn't get picked up by PyPi.

**Comment by davidmegginson** [comment]
Resolved: https://github.com/davidmegginson/python-io-wrapper/issues/1

**Comment by kynan** [comment]
Dependencies:
* [ ] hdx-python-utilities>=3.4.7
* [ ] libhxl>=4.27
* [x] pyphonetics

**Comment by kynan** [comment]
All prerequisites are now packaged. Sent conda-forge/staged-recipes#21984

**Comment by kynan** [comment]
Done! [Package is now live](https://anaconda.org/conda-forge/hdx-python-country) @mcarans @turnerm

**Comment by kynan** [comment]
I can't seem to mark this issue fixed though 🤔

**Comment by mcarans** [comment]
Closing
