### ISSUE TITLE
Separate live mode from the package?

### ISSUE THREAD

**Issue by killthekitten** [OCHA-DAP/hdx-python-country#4]
Really good job on the package! However, it's dragging a lot of unwanted dependencies that raise security concerns:

```
cffi>=1.1->bcrypt>=3.1.3->paramiko>=1.15.2->sshtunnel->hdx-python-utilities>=1.7.8->hdx-python-country==2.1.2
```

It would be better to have the live mode set up as a package extra, something like `hdx-python-country[with_live_mode]`, which would then drag all the `hdx-python-utilities` machinery including `sshtunnel` and such.

Is it something worth spending time on?

**Comment by mcarans** [comment]
Sorry I only just saw this as I thought this package was only used in our team. You are right. The change you suggested would be good.

**Comment by mcarans** [comment]
I have moved the database code from the dependent HDX Python Utilities library into a new and separate HDX Python Database library and removed the depencies on sshtunnel and psycopg2-binary.

**Comment by mcarans** [comment]
@killthekitten Please let me know if this solves this issue for you. If not, please let me know what other dependencies are an issue.

**Comment by killthekitten** [comment]
@mcarans thanks, looks good now!

**Comment by mcarans** [comment]
Great, closing issue.
