### ISSUE TITLE
How to extend country data with extra HXL data

### ISSUE THREAD

**Issue by garrettc** [OCHA-DAP/hdx-python-country#57]
(I looked through the documentation and code, so apologies if I've missed something obvious)

We'd like to incorporate extra data in the return from `get_country_info_from_*`, specifically the categorisation for:

- Least Developed Countries (LDC)
- Land Locked Developing Countries (LLDC)
- Small Island Developing States (SIDS)

from the [UN M49 dataset](https://unstats.un.org/unsd/methodology/m49/overview/).

Is there a recommended way of doing this? The closest I can see is cloning the OCHA csv file, adding our own data, then using `set_ocha_url()` to point to our file.

**Comment by mcarans** [comment]
The method you've described should work. We can look at adding those fields to our dataset in future.

**Comment by garrettc** [comment]
Great, thank you. We'll proceed along those lines.
