### ISSUE TITLE
set_use_live_default not working as expected

### ISSUE THREAD

**Issue by andy-isoc** [OCHA-DAP/hdx-python-country#62]
I have called `Country.set_use_live_default(False)` but when calling any method to retrieve data, it's still using the live data. It seems to be setting `cls._use_live` correctly but the method param default is not picking this value up.

I will submit a PR for a fix.

**Comment by mcarans** [comment]
@andy-isoc Please confirm if 3.8.5 which has your fix resolves this issue

**Comment by andy-isoc** [comment]
@mcarans Many thanks for prompt review/merge/release. Yes, this does indeed fix the issue for us.
